# Phase 2

# Understanding the Dataset

## Examing Data Stucture and Field Types

### Customer Dataset

In [3]:
import pandas as pd

# Load dataset
customers_df = pd.read_excel("C:\\Anitha\\NIIT\\Capstone Project\\capstone-project-retail-tech\\Data Set\\Customers_dataset.xlsx")

# 1. Number of rows and columns
print("Dataset Shape:")
print(customers_df.shape)

# 2. Column names
print("\nColumn Names:")
print(customers_df.columns.tolist())

# 3. Structure and data types
print("\nDataset Information:")
customers_df.info()

# 4. Data types only
print("\nField Data Types:")
print(customers_df.dtypes)

# 5. First 5 records
print("\nFirst 5 Records:")
print(customers_df.head())

Dataset Shape:
(90000, 5)

Column Names:
['customer_id', 'customer_zip_code', 'gender', 'age_group', 'customer_segment']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        90000 non-null  object
 1   customer_zip_code  90000 non-null  int64
 2   gender             90000 non-null  object
 3   age_group          90000 non-null  object
 4   customer_segment   90000 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.4+ MB

Field Data Types:
customer_id          object
customer_zip_code     int64
gender               object
age_group            object
customer_segment     object
dtype: object

First 5 Records:
  customer_id  customer_zip_code  gender age_group customer_segment
0      C00001             690511  Female     36-45            Loyal
1      C00002             509152    Male     26-35              New
2      C00003             477335    Male     26-35            Loyal
3      C00004             140413  Female       65+            Loyal
4      C00005             700009    Male     26-35            Loyal

In [4]:
print("Changing the Data types")
customers_df["customer_zip_code"] = customers_df["customer_zip_code"].astype("string")
print(customers_df.dtypes)

Changing the Data types
customer_id                  object
customer_zip_code    string[python]
gender                       object
age_group                    object
customer_segment             object
dtype: object

### Geolocation Dataset

In [5]:


# Load dataset
geo_df = pd.read_excel("C:\\Anitha\\NIIT\Capstone Project\\capstone-project-retail-tech\\Data Set\\Geolocation_dataset.xlsx")

# 1. Number of rows and columns
print("Dataset Shape:")
print(geo_df.shape)

# 2. Column names
print("\nColumn Names:")
print(geo_df.columns.tolist())

# 3. Structure and data types
print("\nDataset Information:")
geo_df.info()

# 4. Data types only
print("\nField Data Types:")
print(geo_df.dtypes)

# 5. First 5 records
print("\nFirst 5 Records:")
print(geo_df.head())

<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:2: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Anitha R\AppData\Local\Temp\ipykernel_18416\1699160218.py:2: SyntaxWarning: invalid escape sequence '\C'
  geo_df = pd.read_excel("C:\\Anitha\\NIIT\Capstone Project\\capstone-project-retail-tech\\Data Set\\Geolocation_dataset.xlsx")

Dataset Shape:
(155545, 6)

Column Names:
['geolocation_zip_code', 'geolocation_city', 'geolocation_state', 'geolocation_lat', 'geolocation_lng', 'region']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155545 entries, 0 to 155544
Data columns (total 6 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   geolocation_zip_code  155545 non-null  int64
 1   geolocation_city      155544 non-null  object
 2   geolocation_state     155545 non-null  object
 3   geolocation_lat       155545 non-null  float64
 4   geolocation_lng       155545 non-null  float64
 5   region                155545 non-null  object
dtypes: float64(2), int64(1), object(3)
memory usage: 7.1+ MB

Field Data Types:
geolocation_zip_code      int64
geolocation_city         object
geolocation_state        object
geolocation_lat         float64
geolocation_lng         float64
region                   object
dtype: object

First 5 Records:
   geolocation_zip_code geolocation_city          geolocation_state  \
0                744301            Sawai  Andaman & Nicobar Islands
1                744301              Mus  Andaman & Nicobar Islands
2                744301           Kakana  Andaman & Nicobar Islands
3                744301       Carnicobar  Andaman & Nicobar Islands
4                744301          Lapathy  Andaman & Nicobar Islands

   geolocation_lat  geolocation_lng region
0           7.5166          93.6031   East
1           9.2333          92.7833   East
2           9.1167          92.8000   East
3           9.1833          92.7667   East
4           9.1833          92.7667   East

In [6]:
print("Changing the Data types")
geo_df["geolocation_zip_code"] = geo_df["geolocation_zip_code"].astype("string")
print(customers_df.dtypes)

Changing the Data types
customer_id                  object
customer_zip_code    string[python]
gender                       object
age_group                    object
customer_segment             object
dtype: object

### Order Items Dataset

In [7]:
# Load dataset
order_items_df = pd.read_excel("C:\\Anitha\\NIIT\\Capstone Project\\capstone-project-retail-tech\\Data Set\\Order_items_dataset.xlsx")

# 1. Number of rows and columns
print("Dataset Shape:")
print(order_items_df.shape)

# 2. Column names
print("\nColumn Names:")
print(order_items_df.columns.tolist())

# 3. Structure and data types
print("\nDataset Information:")
order_items_df.info()

# 4. Data types only
print("\nField Data Types:")
print(order_items_df.dtypes)

# 5. First 5 records
print("\nFirst 5 Records:")
print(order_items_df.head())

Dataset Shape:
(150000, 7)

Column Names:
['order_item_id', 'order_id', 'quantity', 'product_id', 'unit_price', 'discount(%)', 'shipping_cost']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  150000 non-null  object
 1   order_id       150000 non-null  object
 2   quantity       150000 non-null  int64
 3   product_id     150000 non-null  object
 4   unit_price     150000 non-null  int64
 5   discount(%)    150000 non-null  float64
 6   shipping_cost  150000 non-null  float64
dtypes: float64(2), int64(2), object(3)
memory usage: 8.0+ MB

Field Data Types:
order_item_id     object
order_id          object
quantity           int64
product_id        object
unit_price         int64
discount(%)      float64
shipping_cost    float64
dtype: object

First 5 Records:
  order_item_id order_id  quantity product_id  unit_price  discount(%)  \
0      OI000001   O00001         1     P28355        7020         6.54
1      OI000002   O00002         1     P04408        7590        20.56
2      OI000003   O00002         2     P14887       14360        24.67
3      OI000004   O00003         2     P02014        1530        12.06
4      OI000005   O00003         1     P27255        1560        10.51

   shipping_cost
0         713.72
1        1212.02
2        1478.39
3         155.12
4         188.03

In [8]:
print("Changing the Data types")
order_items_df["unit_price"] = order_items_df["unit_price"].astype("float")
print(order_items_df.dtypes)

Changing the Data types
order_item_id     object
order_id          object
quantity           int64
product_id        object
unit_price       float64
discount(%)      float64
shipping_cost    float64
dtype: object

### Order Reviews Dataset

In [9]:
# Load dataset
order_reviews_df = pd.read_excel("C:\\Anitha\\NIIT\\Capstone Project\\capstone-project-retail-tech\\Data Set\\Order_reviews_dataset.xlsx")

# 1. Number of rows and columns
print("Dataset Shape:")
print(order_reviews_df.shape)

# 2. Column names
print("\nColumn Names:")
print(order_reviews_df.columns.tolist())

# 3. Structure and data types
print("\nDataset Information:")
order_reviews_df.info()

# 4. Data types only
print("\nField Data Types:")
print(order_reviews_df.dtypes)

# 5. First 5 records
print("\nFirst 5 Records:")
print(order_reviews_df.head())

Dataset Shape:
(97019, 5)

Column Names:
['review_id', 'order_id', 'review_score', 'review_comment_message', 'review_date']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97019 entries, 0 to 97018
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   review_id               97019 non-null  object
 1   order_id                97019 non-null  object
 2   review_score            97019 non-null  int64
 3   review_comment_message  56169 non-null  object
 4   review_date             49465 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 3.7+ MB

Field Data Types:
review_id                         object
order_id                          object
review_score                       int64
review_comment_message            object
review_date               datetime64[ns]
dtype: object

First 5 Records:
  review_id order_id  review_score              review_comment_message  \
0    R00001   O41195             5                                 NaN
1    R00002   O29304             5      Order cancelled by the seller.
2    R00003   O57427             5  Payment issue led to cancellation.
3    R00004   O12705             5                                 NaN
4    R00005   O43324             1                                 NaN

  review_date
0         NaT
1         NaT
2         NaT
3  2022-10-22
4         NaT

### Orders Dataset

In [10]:
# Load dataset
orders_df = pd.read_excel("C:\\Anitha\\NIIT\\Capstone Project\\capstone-project-retail-tech\\Data Set\\Orders_dataset.xlsx")

# 1. Number of rows and columns
print("Dataset Shape:")
print(orders_df.shape)

# 2. Column names
print("\nColumn Names:")
print(orders_df.columns.tolist())

# 3. Structure and data types
print("\nDataset Information:")
orders_df.info()

# 4. Data types only
print("\nField Data Types:")
print(orders_df.dtypes)

# 5. First 5 records
print("\nFirst 5 Records:")
print(orders_df.head())

Dataset Shape:
(99999, 9)

Column Names:
['order_id', 'customer_id', 'order_status', 'payment_type', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_shipping_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99999 non-null  object
 1   customer_id                    99999 non-null  object
 2   order_status                   99999 non-null  object
 3   payment_type                   99999 non-null  object
 4   order_purchase_timestamp       99999 non-null  datetime64[ns]
 5   order_approved_at              94951 non-null  datetime64[ns]
 6   order_delivered_shipping_date  94951 non-null  datetime64[ns]
 7   order_delivered_customer_date  91971 non-null  datetime64[ns]
 8   order_estimated_delivery_date  94951 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(4)
memory usage: 6.9+ MB

Field Data Types:
order_id                                 object
customer_id                              object
order_status                             object
payment_type                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_shipping_date    datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

First 5 Records:
  order_id customer_id order_status payment_type order_purchase_timestamp  \
0   O00001      C60210    delivered  Net Banking               2024-11-04
1   O00002      C01893    delivered  Net Banking               2023-09-01
2   O00003      C19454    cancelled          UPI               2021-08-06
3   O00004      C67148    delivered          UPI               2025-07-07
4   O00005      C56280    delivered  Net Banking               2024-03-30

  order_approved_at order_delivered_shipping_date  \
0        2024-11-04                    2024-12-01
1        2023-09-01                    2023-10-01
2               NaT                           NaT
3        2025-07-07                    2025-10-06
4        2024-03-30                    2024-03-31

  order_delivered_customer_date order_estimated_delivery_date
0                    2025-03-04                    2025-01-03
1                    2023-10-05                    2023-10-31
2                           NaT                           NaT
3                    2025-10-12                    2025-07-12
4                    2024-04-04                    2024-04-07

### Products Dataset

In [11]:
# Load dataset
products_df = pd.read_excel("C:\\Anitha\\NIIT\\Capstone Project\\capstone-project-retail-tech\\Data Set\\Products_dataset.xlsx")

# 1. Number of rows and columns
print("Dataset Shape:")
print(products_df.shape)

# 2. Column names
print("\nColumn Names:")
print(products_df.columns.tolist())

# 3. Structure and data types
print("\nDataset Information:")
products_df.info()

# 4. Data types only
print("\nField Data Types:")
print(products_df.dtypes)

# 5. First 5 records
print("\nFirst 5 Records:")
print(products_df.head())

Dataset Shape:
(32951, 8)

Column Names:
['product_id', 'Category_name', 'sub_category_name', 'product_weight_g', 'brand', 'cost_price', 'selling_price', 'stock_availability']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          32951 non-null  object
 1   Category_name       32951 non-null  object
 2   sub_category_name   32951 non-null  object
 3   product_weight_g    32951 non-null  int64
 4   brand               32951 non-null  object
 5   cost_price          32951 non-null  int64
 6   selling_price       32951 non-null  int64
 7   stock_availability  32951 non-null  object
dtypes: int64(3), object(5)
memory usage: 2.0+ MB

Field Data Types:
product_id            object
Category_name         object
sub_category_name     object
product_weight_g       int64
brand                 object
cost_price             int64
selling_price          int64
stock_availability    object
dtype: object

First 5 Records:
  product_id   Category_name    sub_category_name  product_weight_g  \
0     P00001       perfumery           Fragrances               225
1     P00002             art  General Merchandise              1000
2     P00003  sports_leisure  General Merchandise               154
3     P00004            baby         Collectibles               371
4     P00005      housewares        Novelty Items               625

            brand  cost_price  selling_price stock_availability
0           Nivea        2200           2860           In Stock
1  Generic Global         110            140           In Stock
2  Generic Indian       14680          17170           In Stock
3  Generic Indian        3890           4920           In Stock
4  Generic Indian       12590          16220           In Stock

In [12]:
print("Changing the Data types")
products_df["cost_price"] = products_df["cost_price"].astype("float")
products_df["selling_price"] = products_df["selling_price"].astype("float")
print(products_df.dtypes)

Changing the Data types
product_id             object
Category_name          object
sub_category_name      object
product_weight_g        int64
brand                  object
cost_price            float64
selling_price         float64
stock_availability     object
dtype: object

# Identifying missing values, duplicates and outliers

### Customers Dataset

#### 1. Missing Values

In [13]:
import numpy as np

# Missing values
missing = pd.DataFrame({
    "Column": customers_df.columns,
    "Missing_Values": customers_df.isnull().sum().values,
    "Missing_Percentage": (
        customers_df.isnull().sum().values / len(customers_df) * 100
    ).round(2)
})

print("Missing Value Report:")
print(missing)

Missing Value Report:
              Column  Missing_Values  Missing_Percentage
0        customer_id               0                 0.0
1  customer_zip_code               0                 0.0
2             gender               0                 0.0
3          age_group               0                 0.0
4   customer_segment               0                 0.0

#### 2. Duplicate Records

In [14]:
duplicate_count = customers_df.duplicated().sum()

print("\nNumber of duplicate records:", duplicate_count)

Number of duplicate records: 0

##### Duplicate Records by Customer Id

In [15]:
duplicate_customer_ids = customers_df[
    customers_df["customer_id"].duplicated(keep=False)
]

print(duplicate_customer_ids)

Empty DataFrame
Columns: [customer_id, customer_zip_code, gender, age_group, customer_segment]
Index: []

#### 3. Outliers

In [16]:
numeric_columns = customers_df.select_dtypes(include=np.number).columns

outlier_report = []

for column in numeric_columns:

    Q1 = customers_df[column].quantile(0.25)
    Q3 = customers_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_count = (
        (customers_df[column] < lower_bound) |
        (customers_df[column] > upper_bound)
    ).sum()

    outlier_report.append({
        "Column": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound,
        "Outlier_Count": outlier_count
    })

outlier_report = pd.DataFrame(outlier_report)

print("\nOutlier Report:")
print(outlier_report)

Outlier Report:
Empty DataFrame
Columns: []
Index: []

### Geolocation Dataset

In [17]:
# ==================================================
# 1. MISSING VALUES
# ==================================================

missing_report = pd.DataFrame({
    "Column": geo_df.columns,
    "Missing_Values": geo_df.isnull().sum().values,
    "Missing_Percentage": (
        geo_df.isnull().sum().values / len(geo_df) * 100
    ).round(2)
})

print("===== MISSING VALUE REPORT =====")
print(missing_report)


# ==================================================
# 2. DUPLICATES
# ==================================================

duplicate_count =geo_df.duplicated().sum()

print("\n===== DUPLICATE REPORT =====")
print("Duplicate records:", duplicate_count)


# ==================================================
# 3. OUTLIERS
# ==================================================

numeric_columns = geo_df.select_dtypes(include=np.number).columns

outlier_results = []

for column in numeric_columns:

    Q1 = geo_df[column].quantile(0.25)
    Q3 = geo_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_count = (
        (geo_df[column] < lower_bound) |
        (geo_df[column] > upper_bound)
    ).sum()

    outlier_results.append({
        "Column": column,
        "Outlier_Count": outlier_count,
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound
    })

outlier_report = pd.DataFrame(outlier_results)

print("\n===== OUTLIER REPORT =====")
print(outlier_report)

===== MISSING VALUE REPORT =====
                 Column  Missing_Values  Missing_Percentage
0  geolocation_zip_code               0                 0.0
1      geolocation_city               1                 0.0
2     geolocation_state               0                 0.0
3       geolocation_lat               0                 0.0
4       geolocation_lng               0                 0.0
5                region               0                 0.0

===== DUPLICATE REPORT =====
Duplicate records: 0

===== OUTLIER REPORT =====
            Column  Outlier_Count  Lower_Bound  Upper_Bound
0  geolocation_lat              0       3.8782      39.6278
1  geolocation_lng           1747      65.3186      94.0482

### Order Items Dataset

In [18]:
# ==================================================
# 1. MISSING VALUES
# ==================================================

missing_report = pd.DataFrame({
    "Column": order_items_df.columns,
    "Missing_Values": order_items_df.isnull().sum().values,
    "Missing_Percentage": (
        order_items_df.isnull().sum().values / len(order_items_df) * 100
    ).round(2)
})

print("===== MISSING VALUE REPORT =====")
print(missing_report)


# ==================================================
# 2. DUPLICATES
# ==================================================

duplicate_count = order_items_df.duplicated().sum()

print("\n===== DUPLICATE REPORT =====")
print("Duplicate records:", duplicate_count)


# ==================================================
# 3. OUTLIERS
# ==================================================

numeric_columns = order_items_df.select_dtypes(include=np.number).columns

outlier_results = []

for column in numeric_columns:

    Q1 = order_items_df[column].quantile(0.25)
    Q3 = order_items_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_count = (
        (order_items_df[column] < lower_bound) |
        (order_items_df[column] > upper_bound)
    ).sum()

    outlier_results.append({
        "Column": column,
        "Outlier_Count": outlier_count,
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound
    })

outlier_report = pd.DataFrame(outlier_results)

print("\n===== OUTLIER REPORT =====")
print(outlier_report)

===== MISSING VALUE REPORT =====
          Column  Missing_Values  Missing_Percentage
0  order_item_id               0                 0.0
1       order_id               0                 0.0
2       quantity               0                 0.0
3     product_id               0                 0.0
4     unit_price               0                 0.0
5    discount(%)               0                 0.0
6  shipping_cost               0                 0.0

===== DUPLICATE REPORT =====
Duplicate records: 0

===== OUTLIER REPORT =====
          Column  Outlier_Count  Lower_Bound  Upper_Bound
0       quantity          37223         1.00         1.00
1     unit_price           5767     -6410.00     16070.00
2    discount(%)           2775       -11.18        36.58
3  shipping_cost          10996      -662.82      1580.22

### Order Reviews Dataset

In [19]:
# ==================================================
# 1. MISSING VALUES
# ==================================================

missing_report = pd.DataFrame({
    "Column": order_reviews_df.columns,
    "Missing_Values": order_reviews_df.isnull().sum().values,
    "Missing_Percentage": (
        order_reviews_df.isnull().sum().values / len(order_reviews_df) * 100
    ).round(2)
})

print("===== MISSING VALUE REPORT =====")
print(missing_report)


# ==================================================
# 2. DUPLICATES
# ==================================================

duplicate_count = order_reviews_df.duplicated().sum()

print("\n===== DUPLICATE REPORT =====")
print("Duplicate records:", duplicate_count)


# ==================================================
# 3. OUTLIERS
# ==================================================

numeric_columns = order_reviews_df.select_dtypes(include=np.number).columns

outlier_results = []

for column in numeric_columns:

    Q1 = order_reviews_df[column].quantile(0.25)
    Q3 = order_reviews_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_count = (
        (order_reviews_df[column] < lower_bound) |
        (order_reviews_df[column] > upper_bound)
    ).sum()

    outlier_results.append({
        "Column": column,
        "Outlier_Count": outlier_count,
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound
    })

outlier_report = pd.DataFrame(outlier_results)

print("\n===== OUTLIER REPORT =====")
print(outlier_report)

===== MISSING VALUE REPORT =====
                   Column  Missing_Values  Missing_Percentage
0               review_id               0                0.00
1                order_id               0                0.00
2            review_score               0                0.00
3  review_comment_message           40850               42.11
4             review_date           47554               49.02

===== DUPLICATE REPORT =====
Duplicate records: 0

===== OUTLIER REPORT =====
         Column  Outlier_Count  Lower_Bound  Upper_Bound
0  review_score          14157          2.5          6.5

### Orders Dataset

In [20]:
# ==================================================
# 1. MISSING VALUES
# ==================================================

missing_report = pd.DataFrame({
    "Column": orders_df.columns,
    "Missing_Values": orders_df.isnull().sum().values,
    "Missing_Percentage": (
        orders_df.isnull().sum().values / len(orders_df) * 100
    ).round(2)
})

print("===== MISSING VALUE REPORT =====")
print(missing_report)


# ==================================================
# 2. DUPLICATES
# ==================================================

duplicate_count = orders_df.duplicated().sum()

print("\n===== DUPLICATE REPORT =====")
print("Duplicate records:", duplicate_count)


# ==================================================
# 3. OUTLIERS
# ==================================================

numeric_columns = orders_df.select_dtypes(include=np.number).columns

outlier_results = []

for column in numeric_columns:

    Q1 = orders_df[column].quantile(0.25)
    Q3 = orders_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_count = (
        (orders_df[column] < lower_bound) |
        (orders_df[column] > upper_bound)
    ).sum()

    outlier_results.append({
        "Column": column,
        "Outlier_Count": outlier_count,
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound
    })

outlier_report = pd.DataFrame(outlier_results)

print("\n===== OUTLIER REPORT =====")
print(outlier_report)

===== MISSING VALUE REPORT =====
                          Column  Missing_Values  Missing_Percentage
0                       order_id               0                0.00
1                    customer_id               0                0.00
2                   order_status               0                0.00
3                   payment_type               0                0.00
4       order_purchase_timestamp               0                0.00
5              order_approved_at            5048                5.05
6  order_delivered_shipping_date            5048                5.05
7  order_delivered_customer_date            8028                8.03
8  order_estimated_delivery_date            5048                5.05

===== DUPLICATE REPORT =====
Duplicate records: 0

===== OUTLIER REPORT =====
Empty DataFrame
Columns: []
Index: []

### Products Dataset

In [21]:
# ==================================================
# 1. MISSING VALUES
# ==================================================

missing_report = pd.DataFrame({
    "Column": products_df.columns,
    "Missing_Values": products_df.isnull().sum().values,
    "Missing_Percentage": (
        products_df.isnull().sum().values / len(products_df) * 100
    ).round(2)
})

print("===== MISSING VALUE REPORT =====")
print(missing_report)


# ==================================================
# 2. DUPLICATES
# ==================================================

duplicate_count = products_df.duplicated().sum()

print("\n===== DUPLICATE REPORT =====")
print("Duplicate records:", duplicate_count)


# ==================================================
# 3. OUTLIERS
# ==================================================

numeric_columns = products_df.select_dtypes(include=np.number).columns

outlier_results = []

for column in numeric_columns:

    Q1 = products_df[column].quantile(0.25)
    Q3 = products_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_count = (
        (products_df[column] < lower_bound) |
        (products_df[column] > upper_bound)
    ).sum()

    outlier_results.append({
        "Column": column,
        "Outlier_Count": outlier_count,
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound
    })

outlier_report = pd.DataFrame(outlier_results)

print("\n===== OUTLIER REPORT =====")
print(outlier_report)

===== MISSING VALUE REPORT =====
               Column  Missing_Values  Missing_Percentage
0          product_id               0                 0.0
1       Category_name               0                 0.0
2   sub_category_name               0                 0.0
3    product_weight_g               0                 0.0
4               brand               0                 0.0
5          cost_price               0                 0.0
6       selling_price               0                 0.0
7  stock_availability               0                 0.0

===== DUPLICATE REPORT =====
Duplicate records: 0

===== OUTLIER REPORT =====
             Column  Outlier_Count  Lower_Bound  Upper_Bound
0  product_weight_g           4564      -2100.0       4300.0
1        cost_price           4841     -12547.5      29752.5
2     selling_price           4839     -15025.0      36615.0

## Document Data Attributes and Metadata

In [66]:

def get_attribute_type(series):
    if pd.api.types.is_datetime64_any_dtype(series):
        return "Date/Time"
    elif pd.api.types.is_numeric_dtype(series):
        return "Numerical"
    elif pd.api.types.is_string_dtype(series):
        return "Categorical/Text"
    else:
        return "Other"


def create_metadata(df, dataset_name):

    return pd.DataFrame({
        "Dataset": dataset_name,
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str).values,
        "Attribute_Type": [
            get_attribute_type(df[col])
            for col in df.columns
        ],
        "Non_Null_Count": df.notna().sum().values,
        "Missing_Values": df.isna().sum().values,
        "Missing_Percentage": (
            df.isna().mean().values * 100
        ).round(2),
        "Unique_Values": df.nunique().values
    })


# Create metadata
metadata_df = pd.concat([
    create_metadata(customers_df, "Customers"),
    create_metadata(products_df, "Products"),
    create_metadata(orders_df, "Orders"),
    create_metadata(order_items_df, "Order Items"),
    create_metadata(order_reviews_df, "Order Reviews"),
    create_metadata(geo_df, "Geolocation")
], ignore_index=True)


# Save to Excel
metadata_df.to_excel(
    "Data_Metadata.xlsx",
    index=False
)

print("Data_Metadata.xlsx created successfully!")

Data_Metadata.xlsx created successfully!

# Data Cleaning and Preprocessing

## Handle missing values systematically

### Geolocation Dataset

In [22]:
geo_df["geolocation_city"] = geo_df["geolocation_city"].fillna("UnKnown")
geo_df.isnull().sum()

geolocation_zip_code    0
geolocation_city        0
geolocation_state       0
geolocation_lat         0
geolocation_lng         0
region                  0
dtype: int64

### Order Reviews Dataset

In [23]:
order_reviews_df["review_comment_message"] = order_reviews_df["review_comment_message"].fillna("No comment")

In [24]:
order_reviews_df["review_date"] = pd.to_datetime(order_reviews_df["review_date"], errors = 'coerce')

In [25]:
order_reviews_df.isnull().sum()

review_id                     0
order_id                      0
review_score                  0
review_comment_message        0
review_date               47554
dtype: int64

## Remove Duplicates and Rectify Inconsistencies

### Customers Dataset

In [26]:
customers_df = pd.read_excel("C:\\Anitha\\NIIT\\Capstone Project\\capstone-project-retail-tech\\Data Set\\Customers_dataset.xlsx")
categorical_cols = customers_df.select_dtypes(
    include=["object", "string", "category"]
).columns

print(categorical_cols)

Index(['customer_id', 'gender', 'age_group', 'customer_segment'], dtype='object')

In [27]:
for col in categorical_cols:
    customers_df[col] = (
        customers_df[col]
        .astype("string")
        .str.strip()
   )

customers_df.head()

  customer_id  customer_zip_code  gender age_group customer_segment
0      C00001             690511  Female     36-45            Loyal
1      C00002             509152    Male     26-35              New
2      C00003             477335    Male     26-35            Loyal
3      C00004             140413  Female       65+            Loyal
4      C00005             700009    Male     26-35            Loyal

### Geolocation Dataset

In [28]:
geo_df = pd.read_excel("C:\\Anitha\\NIIT\\Capstone Project\\capstone-project-retail-tech\\Data Set\\Geolocation_dataset.xlsx")
categorical_cols = geo_df.select_dtypes(
    include=["object", "string", "category"]
).columns

print(categorical_cols)

Index(['geolocation_city', 'geolocation_state', 'region'], dtype='object')

In [29]:
for col in categorical_cols:
    geo_df[col] = (
        geo_df[col]
        .astype("string")
        .str.strip()    )
geo_df.head()

,geolocation_zip_code,geolocation_city,geolocation_state,geolocation_lat,geolocation_lng,region
0,744301,Sawai,Andaman & Nicobar Islands,7.5166,93.6031,East
1,744301,Mus,Andaman & Nicobar Islands,9.2333,92.7833,East
2,744301,Kakana,Andaman & Nicobar Islands,9.1167,92.8000,East
3,744301,Carnicobar,Andaman & Nicobar Islands,9.1833,92.7667,East
4,744301,Lapathy,Andaman & Nicobar Islands,9.1833,92.7667,East

Order items Dataset

In [30]:
categorical_cols = order_items_df.select_dtypes(
    include=["object", "string", "category"]
).columns

print(categorical_cols)

Index(['order_item_id', 'order_id', 'product_id'], dtype='object')

In [31]:
for col in categorical_cols:
    order_items_df[col] = (
        order_items_df[col]
        .astype("string")
        .str.strip()
           )
order_items_df.head()

,order_item_id,order_id,quantity,product_id,unit_price,discount(%),shipping_cost
0,OI000001,O00001,1,P28355,7020.0,6.54,713.72
1,OI000002,O00002,1,P04408,7590.0,20.56,1212.02
2,OI000003,O00002,2,P14887,14360.0,24.67,1478.39
3,OI000004,O00003,2,P02014,1530.0,12.06,155.12
4,OI000005,O00003,1,P27255,1560.0,10.51,188.03

### Order Reviews Dataset

In [32]:
categorical_cols = order_reviews_df.select_dtypes(
    include=["object", "string", "category"]
).columns

print(categorical_cols)

Index(['review_id', 'order_id', 'review_comment_message'], dtype='object')

In [33]:
for col in categorical_cols:
    order_reviews_df[col] = (
        order_reviews_df[col]
        .astype("string")
        .str.strip()
    )
order_reviews_df.head()

,review_id,order_id,review_score,review_comment_message,review_date
0,R00001,O41195,5,No comment,NaT
1,R00002,O29304,5,Order cancelled by the seller.,NaT
2,R00003,O57427,5,Payment issue led to cancellation.,NaT
3,R00004,O12705,5,No comment,2022-10-22
4,R00005,O43324,1,No comment,NaT

### Orders Dataset

In [34]:
categorical_cols = orders_df.select_dtypes(
    include=["object", "string", "category"]
).columns

print(categorical_cols)

Index(['order_id', 'customer_id', 'order_status', 'payment_type'], dtype='object')

In [35]:
for col in categorical_cols:
    orders_df[col] = (
        orders_df[col]
        .astype("string")
        .str.strip()
    )

orders_df.head()

,order_id,customer_id,order_status,payment_type,order_purchase_timestamp,order_approved_at,order_delivered_shipping_date,order_delivered_customer_date,order_estimated_delivery_date
0,O00001,C60210,delivered,Net Banking,2024-11-04,2024-11-04,2024-12-01,2025-03-04,2025-01-03
1,O00002,C01893,delivered,Net Banking,2023-09-01,2023-09-01,2023-10-01,2023-10-05,2023-10-31
2,O00003,C19454,cancelled,UPI,2021-08-06,NaT,NaT,NaT,NaT
3,O00004,C67148,delivered,UPI,2025-07-07,2025-07-07,2025-10-06,2025-10-12,2025-07-12
4,O00005,C56280,delivered,Net Banking,2024-03-30,2024-03-30,2024-03-31,2024-04-04,2024-04-07

### Products Dataset

In [36]:
categorical_cols = products_df.select_dtypes(
    include=["object", "string", "category"]
).columns

print(categorical_cols)

Index(['product_id', 'Category_name', 'sub_category_name', 'brand',
       'stock_availability'],
      dtype='object')

In [37]:
for col in categorical_cols:
    products_df[col] = (
        products_df[col]
        .astype("string")
        .str.strip()
    )
products_df.head()

,product_id,Category_name,sub_category_name,product_weight_g,brand,cost_price,selling_price,stock_availability
0,P00001,perfumery,Fragrances,225,Nivea,2200.0,2860.0,In Stock
1,P00002,art,General Merchandise,1000,Generic Global,110.0,140.0,In Stock
2,P00003,sports_leisure,General Merchandise,154,Generic Indian,14680.0,17170.0,In Stock
3,P00004,baby,Collectibles,371,Generic Indian,3890.0,4920.0,In Stock
4,P00005,housewares,Novelty Items,625,Generic Indian,12590.0,16220.0,In Stock

### Check date consistency

In [38]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_shipping_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_cols:
    orders_df[col] = pd.to_datetime(orders_df[col], errors="coerce")

In [39]:
print(orders_df[date_cols].dtypes)

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_shipping_date    datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

## Address Outliers Using Statistical or Logical Methods

In [40]:
order_items_df_clean = order_items_df.copy()

order_items_df_clean.loc[order_items_df_clean["unit_price"] <= 0, "unit_price"] = np.nan
order_items_df_clean["unit_price"] = order_items_df_clean["unit_price"].fillna(
    order_items_df_clean["unit_price"].median()
)

order_items_df_clean.loc[
    (order_items_df_clean["discount(%)"] < 0) |
    (order_items_df_clean["discount(%)"] > 100),
    "discount(%)"
] = np.nan
order_items_df_clean["discount(%)"] = order_items_df_clean["discount(%)"].fillna(
    order_items_df_clean["discount(%)"].median()
)

order_items_df_clean.loc[order_items_df_clean["shipping_cost"] < 0, "shipping_cost"] = np.nan
order_items_df_clean["shipping_cost"] = order_items_df_clean["shipping_cost"].fillna(
    order_items_df_clean["shipping_cost"].median()
)

#### Check the result

In [41]:
print("Quantity invalid:",
      (order_items_df_clean["quantity"] <= 0).sum())

print("Unit price invalid:",
      (order_items_df_clean["unit_price"] <= 0).sum())

print("Discount invalid:",
      ((order_items_df_clean["discount(%)"] < 0) |
       (order_items_df_clean["discount(%)"] > 100)).sum())

print("Shipping cost invalid:",
      (order_items_df_clean["shipping_cost"] < 0).sum())

Quantity invalid: 0
Unit price invalid: 0
Discount invalid: 0
Shipping cost invalid: 0

#### Verify

In [42]:
order_items_df_clean[[
    "quantity",
    "unit_price",
    "discount(%)",
    "shipping_cost"
]].describe()

           quantity     unit_price    discount(%)  shipping_cost
count  150000.00000  150000.000000  150000.000000  150000.000000
mean        1.28356    6781.045333      13.526562     722.353992
std         0.52342   12494.025679       9.086881    1610.289245
min         1.00000      50.000000       0.000000       5.000000
25%         1.00000    2020.000000       6.730000     178.320000
50%         1.00000    4030.000000      12.280000     380.930000
75%         1.00000    7640.000000      18.670000     739.080000
max         3.00000  149760.000000      52.490000   29830.680000

### Order Reviews Dataset

In [43]:
invalid_scores = order_reviews_df[
    (order_reviews_df["review_score"] < 1) |
    (order_reviews_df["review_score"] > 5)
]

print("Invalid review scores:", len(invalid_scores))
print(invalid_scores["review_score"].unique())

Invalid review scores: 0
[]

### Products Dataset

In [44]:
print("Negative weights:",
      (products_df["product_weight_g"] < 0).sum())

Negative weights: 0

In [45]:
print("Invalid cost prices:",
      (products_df["cost_price"] <= 0).sum())

Invalid cost prices: 0

In [46]:
print("Invalid selling prices:",
      (products_df["selling_price"] <= 0).sum())

Invalid selling prices: 0

## Maintaining a Preprocessing Log for Tranparency

### Customer Dataset

In [59]:
preprocessing_log = [
    {
        "Step": 1,
        "Dataset": "All datasets",
        "Column": "All columns",
        "Issue": "Data structure and field types",
        "Method": "Data profiling",
        "Action Taken": "Examined rows, columns and data types",
        "Reason": "To understand the dataset before cleaning"
    },
    {
        "Step": 2,
        "Dataset": "Products",
        "Column": "customer_zip_code",
        "Issue": "Incorrect data type",
        "Method": "Data type conversion",
        "Action Taken": "Converted integer to string",
        "Reason": "ZIP code is a location identifier, not a numerical measurement"
    },
    {
        "Step": 3,
        "Dataset": "Orders",
        "Column": "order_approved_at",
        "Issue": "5048 missing values",
        "Method": "Missing-value analysis",
        "Action Taken": "Missing values retained",
        "Reason": "Missing date may have business meaning"
    },
    {
        "Step": 4,
        "Dataset": "Orders",
        "Column": "order_delivered_shipping_date",
        "Issue": "5048 missing values",
        "Method": "Missing-value analysis",
        "Action Taken": "Missing values retained",
        "Reason": "Order may not have been shipped"
    },
    {
        "Step": 5,
        "Dataset": "Orders",
        "Column": "order_delivered_customer_date",
        "Issue": "8028 missing values",
        "Method": "Missing-value analysis",
        "Action Taken": "Missing values retained",
        "Reason": "Order may not have been delivered"
    },
    {
        "Step": 6,
        "Dataset": "Orders",
        "Column": "order_estimated_delivery_date",
        "Issue": "5048 missing values",
        "Method": "Missing-value analysis",
        "Action Taken": "Missing values retained",
        "Reason": "Missing date may depend on order status"
    },
    {
        "Step": 7,
        "Dataset": "Orders",
        "Column": "All columns",
        "Issue": "Duplicate records",
        "Method": "Duplicate detection",
        "Action Taken": "No records removed",
        "Reason": "Duplicate count was 0"
    },
    {
        "Step": 8,
        "Dataset": "Orders",
        "Column": "order_status",
        "Issue": "Potential inconsistency",
        "Method": "Consistency check",
        "Action Taken": "Checked and standardized formatting",
        "Reason": "To maintain consistent categories"
    },
    {
        "Step": 9,
        "Dataset": "All datasets",
        "Column": "All text columns",
        "Issue": "Leading and trailing whitespace",
        "Method": "String standardization",
        "Action Taken": "Applied strip() to text columns",
        "Reason": "To remove unwanted leading and trailing spaces and maintain consistent values"
    },
    {
        "Step": 10,
        "Dataset": "Orders",
        "Column": "Date columns",
        "Issue": "Date type consistency",
        "Method": "Data type conversion",
        "Action Taken": "Converted to datetime",
        "Reason": "Required for date analysis"
    },
    {
        "Step": 11,
        "Dataset": "Order Items",
        "Column": "quantity",
        "Issue": "37223 statistical outliers",
        "Method": "IQR + logical validation",
        "Action Taken": "Investigated using business rules",
        "Reason": "Quantity greater than 1 can be valid"
    },
    {
        "Step": 12,
        "Dataset": "Order Itemss",
        "Column": "unit_price",
        "Issue": "5767 statistical outliers",
        "Method": "IQR + logical validation",
        "Action Taken": "Investigated extreme values",
        "Reason": "High prices can be legitimate"
    },
    {
        "Step": 13,
        "Dataset": "Order Items",
        "Column": "discount(%)",
        "Issue": "2775 statistical outliers",
        "Method": "IQR + logical validation",
        "Action Taken": "Checked valid discount range",
        "Reason": "Discount must follow business rules"
    },
    {
        "Step": 14,
        "Dataset": "Order Items",
        "Column": "shipping_cost",
        "Issue": "10996 statistical outliers",
        "Method": "IQR + logical validation",
        "Action Taken": "Investigated extreme values",
        "Reason": "High shipping cost can be legitimate"
    },
    {
        "Step": 15,
        "Dataset": "Geolocation",
        "Column": "geolocation_lat",
        "Issue": "No statistical outliers",
        "Method": "IQR",
        "Action Taken": "No action",
        "Reason": "No IQR outliers detected"
    },
    {
        "Step": 16,
        "Dataset": "Geolocation",
        "Column": "geolocation_lng",
        "Issue": "1747 statistical outliers",
        "Method": "IQR + geographical validation",
        "Action Taken": "Validated geographic range",
        "Reason": "Statistical outlier does not necessarily mean invalid coordinate"
    },
    {
        "Step": 17,
        "Dataset": "Order Reviews",
        "Column": "review_score",
        "Issue": "14157 statistical outliers",
        "Method": "IQR + logical validation",
        "Action Taken": "Validated against rating scale",
        "Reason": "Low ratings can be legitimate"
    },
    {
        "Step": 18,
        "Dataset": "Products",
        "Column": "product_weight_g",
        "Issue": "4564 statistical outliers",
        "Method": "IQR + logical validation",
        "Action Taken": "Checked for invalid values",
        "Reason": "Extreme weight can be legitimate"
    },
    {
        "Step": 19,
        "Dataset": "Products",
        "Column": "cost_price",
        "Issue": "4841 statistical outliers",
        "Method": "IQR + logical validation",
        "Action Taken": "Checked for invalid values",
        "Reason": "High cost can be legitimate"
    },
    {
        "Step": 20,
        "Dataset": "Products",
        "Column": "selling_price",
        "Issue": "4839 statistical outliers",
        "Method": "IQR + logical validation",
        "Action Taken": "Checked for invalid values",
        "Reason": "High selling price can be legitimate"
    }
]

# Create DataFrame
log_df = pd.DataFrame(preprocessing_log)
log_df = log_df.drop_duplicates()
# Display
print(log_df)

# Export to Excel
log_df.to_excel(
    "Preprocessing_Log.xlsx",
    index=False
)

print("Preprocessing log saved successfully!")

    Step        Dataset                         Column  \
0      1   All datasets                    All columns
1      2       Products              customer_zip_code
2      3         Orders              order_approved_at
3      4         Orders  order_delivered_shipping_date
4      5         Orders  order_delivered_customer_date
5      6         Orders  order_estimated_delivery_date
6      7         Orders                    All columns
7      8         Orders                   order_status
8      9   All datasets               All text columns
9     10         Orders                   Date columns
10    11    Order Items                       quantity
11    12   Order Itemss                     unit_price
12    13    Order Items                    discount(%)
13    14    Order Items                  shipping_cost
14    15    Geolocation                geolocation_lat
15    16    Geolocation                geolocation_lng
16    17  Order Reviews                   review_score
17    18       Products               product_weight_g
18    19       Products                     cost_price
19    20       Products                  selling_price

                              Issue                         Method  \
0    Data structure and field types                 Data profiling
1               Incorrect data type           Data type conversion
2               5048 missing values         Missing-value analysis
3               5048 missing values         Missing-value analysis
4               8028 missing values         Missing-value analysis
5               5048 missing values         Missing-value analysis
6                 Duplicate records            Duplicate detection
7           Potential inconsistency              Consistency check
8   Leading and trailing whitespace         String standardization
9             Date type consistency           Data type conversion
10       37223 statistical outliers       IQR + logical validation
11        5767 statistical outliers       IQR + logical validation
12        2775 statistical outliers       IQR + logical validation
13       10996 statistical outliers       IQR + logical validation
14          No statistical outliers                            IQR
15        1747 statistical outliers  IQR + geographical validation
16       14157 statistical outliers       IQR + logical validation
17        4564 statistical outliers       IQR + logical validation
18        4841 statistical outliers       IQR + logical validation
19        4839 statistical outliers       IQR + logical validation

                             Action Taken  \
0   Examined rows, columns and data types
1             Converted integer to string
2                 Missing values retained
3                 Missing values retained
4                 Missing values retained
5                 Missing values retained
6                      No records removed
7     Checked and standardized formatting
8         Applied strip() to text columns
9                   Converted to datetime
10      Investigated using business rules
11            Investigated extreme values
12           Checked valid discount range
13            Investigated extreme values
14                              No action
15             Validated geographic range
16         Validated against rating scale
17             Checked for invalid values
18             Checked for invalid values
19             Checked for invalid values

                                               Reason
0           To understand the dataset before cleaning
1   ZIP code is a location identifier, not a numer...
2              Missing date may have business meaning
3                     Order may not have been shipped
4                   Order may not have been delivered
5             Missing date may depend on order status
6                               Duplicate count was 0
7                   To maintain consistent categories
8   To remove unwanted leading and trailing spaces...
9                          Required for date analysis
10               Quantity greater than 1 can be valid
11                      High prices can be legitimate
12                Discount must follow business rules
13               High shipping cost can be legitimate
14                           No IQR outliers detected
15  Statistical outlier does not necessarily mean ...
16                      Low ratings can be legitimate
17                   Extreme weight can be legitimate
18                        High cost can be legitimate
19               High selling price can be legitimate
Preprocessing log saved successfully!

# Store Cleaned Data

.xlsx format

In [48]:

customers_df.to_csv("cleaned_customers.csv", index=False)
geo_df.to_csv("cleaned_geolocation.csv", index=False)
order_items_df_clean.to_csv("cleaned_order_items.csv", index=False)
order_reviews_df.to_csv("cleaned_order_reviews.csv", index=False)
orders_df.to_csv("cleaned_orders.csv", index=False)
products_df.to_csv("cleaned_products.csv", index=False)
print("Cleaned data exported to csv successfully.")

Cleaned data exported to csv successfully.

## Database(MySQL)

In [49]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:root@localhost/retailtech"
)

In [54]:
customers_df.to_sql(
    "customers",
    con=engine,
    if_exists="replace",
    index=False
)

geo_df.to_sql(
    "geolocation",
    con=engine,
    if_exists="replace",
    index=False
)

order_items_df_clean.to_sql(
    "order_items",
    con=engine,
    if_exists="replace",
    index=False
)

order_reviews_df.to_sql(
    "order_reviews",
    con=engine,
    if_exists="replace",
    index=False
)

orders_df.to_sql(
    "orders",
    con=engine,
    if_exists="replace",
    index=False
)

products_df.to_sql(
    "products",
    con=engine,
    if_exists="replace",
    index=False
)

print("DataFrame loaded to MySQL Successfully")

DataFrame loaded to MySQL Successfully

## Enable Accessibilty and Scalability across the Project

In [62]:
preprocessing_log.append({
    "Step": 21,
    "Dataset": "All cleaned datasets",
    "Column": "All columns",
    "Issue": "Data accessibility and scalability",
    "Method": "Data storage",
    "Action Taken": "Stored cleaned data in CSV and MySQL",
    "Reason": "To make cleaned data accessible for analysis and support scalable data storage"
})

In [63]:
# Create DataFrame
log_df = pd.DataFrame(preprocessing_log)

log_df = log_df.drop_duplicates()
# Display
print(log_df)

# Export to Excel
log_df.to_excel(
    "Preprocessing_Log.xlsx",
    index=False
)

print("Preprocessing log saved successfully!")

    Step               Dataset                         Column  \
0      1          All datasets                    All columns
1      2              Products              customer_zip_code
2      3                Orders              order_approved_at
3      4                Orders  order_delivered_shipping_date
4      5                Orders  order_delivered_customer_date
5      6                Orders  order_estimated_delivery_date
6      7                Orders                    All columns
7      8                Orders                   order_status
8      9          All datasets               All text columns
9     10                Orders                   Date columns
10    11           Order Items                       quantity
11    12          Order Itemss                     unit_price
12    13           Order Items                    discount(%)
13    14           Order Items                  shipping_cost
14    15           Geolocation                geolocation_lat
15    16           Geolocation                geolocation_lng
16    17         Order Reviews                   review_score
17    18              Products               product_weight_g
18    19              Products                     cost_price
19    20              Products                  selling_price
20    21  All cleaned datasets                    All columns

                                 Issue                         Method  \
0       Data structure and field types                 Data profiling
1                  Incorrect data type           Data type conversion
2                  5048 missing values         Missing-value analysis
3                  5048 missing values         Missing-value analysis
4                  8028 missing values         Missing-value analysis
5                  5048 missing values         Missing-value analysis
6                    Duplicate records            Duplicate detection
7              Potential inconsistency              Consistency check
8      Leading and trailing whitespace         String standardization
9                Date type consistency           Data type conversion
10          37223 statistical outliers       IQR + logical validation
11           5767 statistical outliers       IQR + logical validation
12           2775 statistical outliers       IQR + logical validation
13          10996 statistical outliers       IQR + logical validation
14             No statistical outliers                            IQR
15           1747 statistical outliers  IQR + geographical validation
16          14157 statistical outliers       IQR + logical validation
17           4564 statistical outliers       IQR + logical validation
18           4841 statistical outliers       IQR + logical validation
19           4839 statistical outliers       IQR + logical validation
20  Data accessibility and scalability                   Data storage

                             Action Taken  \
0   Examined rows, columns and data types
1             Converted integer to string
2                 Missing values retained
3                 Missing values retained
4                 Missing values retained
5                 Missing values retained
6                      No records removed
7     Checked and standardized formatting
8         Applied strip() to text columns
9                   Converted to datetime
10      Investigated using business rules
11            Investigated extreme values
12           Checked valid discount range
13            Investigated extreme values
14                              No action
15             Validated geographic range
16         Validated against rating scale
17             Checked for invalid values
18             Checked for invalid values
19             Checked for invalid values
20   Stored cleaned data in CSV and MySQL

                                               Reason
0           To understand the dataset before cleaning
1   ZIP code is a location identifier, not a numer...
2              Missing date may have business meaning
3                     Order may not have been shipped
4                   Order may not have been delivered
5             Missing date may depend on order status
6                               Duplicate count was 0
7                   To maintain consistent categories
8   To remove unwanted leading and trailing spaces...
9                          Required for date analysis
10               Quantity greater than 1 can be valid
11                      High prices can be legitimate
12                Discount must follow business rules
13               High shipping cost can be legitimate
14                           No IQR outliers detected
15  Statistical outlier does not necessarily mean ...
16                      Low ratings can be legitimate
17                   Extreme weight can be legitimate
18                        High cost can be legitimate
19               High selling price can be legitimate
20  To make cleaned data accessible for analysis a...
Preprocessing log saved successfully!

## Ensure standardized schema for reproducibility

In [64]:
preprocessing_log.append({
    "Step": 22,
    "Dataset": "All datasets",
    "Column": "All columns",
    "Issue": "Inconsistent data structure/schema",
    "Method": "Schema standardization",
    "Action Taken": "Standardized column names, data types and column structure",
    "Reason": "To ensure consistent results and reproducibility across preprocessing runs"
})

In [65]:
# Create DataFrame
log_df = pd.DataFrame(preprocessing_log)

log_df = log_df.drop_duplicates()
# Display
print(log_df)

# Export to Excel
log_df.to_excel(
    "Preprocessing_Log.xlsx",
    index=False
)

print("Preprocessing log saved successfully!")

    Step               Dataset                         Column  \
0      1          All datasets                    All columns
1      2              Products              customer_zip_code
2      3                Orders              order_approved_at
3      4                Orders  order_delivered_shipping_date
4      5                Orders  order_delivered_customer_date
5      6                Orders  order_estimated_delivery_date
6      7                Orders                    All columns
7      8                Orders                   order_status
8      9          All datasets               All text columns
9     10                Orders                   Date columns
10    11           Order Items                       quantity
11    12          Order Itemss                     unit_price
12    13           Order Items                    discount(%)
13    14           Order Items                  shipping_cost
14    15           Geolocation                geolocation_lat
15    16           Geolocation                geolocation_lng
16    17         Order Reviews                   review_score
17    18              Products               product_weight_g
18    19              Products                     cost_price
19    20              Products                  selling_price
20    21  All cleaned datasets                    All columns
21    22          All datasets                    All columns

                                 Issue                         Method  \
0       Data structure and field types                 Data profiling
1                  Incorrect data type           Data type conversion
2                  5048 missing values         Missing-value analysis
3                  5048 missing values         Missing-value analysis
4                  8028 missing values         Missing-value analysis
5                  5048 missing values         Missing-value analysis
6                    Duplicate records            Duplicate detection
7              Potential inconsistency              Consistency check
8      Leading and trailing whitespace         String standardization
9                Date type consistency           Data type conversion
10          37223 statistical outliers       IQR + logical validation
11           5767 statistical outliers       IQR + logical validation
12           2775 statistical outliers       IQR + logical validation
13          10996 statistical outliers       IQR + logical validation
14             No statistical outliers                            IQR
15           1747 statistical outliers  IQR + geographical validation
16          14157 statistical outliers       IQR + logical validation
17           4564 statistical outliers       IQR + logical validation
18           4841 statistical outliers       IQR + logical validation
19           4839 statistical outliers       IQR + logical validation
20  Data accessibility and scalability                   Data storage
21  Inconsistent data structure/schema         Schema standardization

                                         Action Taken  \
0               Examined rows, columns and data types
1                         Converted integer to string
2                             Missing values retained
3                             Missing values retained
4                             Missing values retained
5                             Missing values retained
6                                  No records removed
7                 Checked and standardized formatting
8                     Applied strip() to text columns
9                               Converted to datetime
10                  Investigated using business rules
11                        Investigated extreme values
12                       Checked valid discount range
13                        Investigated extreme values
14                                          No action
15                         Validated geographic range
16                     Validated against rating scale
17                         Checked for invalid values
18                         Checked for invalid values
19                         Checked for invalid values
20               Stored cleaned data in CSV and MySQL
21  Standardized column names, data types and colu...

                                               Reason
0           To understand the dataset before cleaning
1   ZIP code is a location identifier, not a numer...
2              Missing date may have business meaning
3                     Order may not have been shipped
4                   Order may not have been delivered
5             Missing date may depend on order status
6                               Duplicate count was 0
7                   To maintain consistent categories
8   To remove unwanted leading and trailing spaces...
9                          Required for date analysis
10               Quantity greater than 1 can be valid
11                      High prices can be legitimate
12                Discount must follow business rules
13               High shipping cost can be legitimate
14                           No IQR outliers detected
15  Statistical outlier does not necessarily mean ...
16                      Low ratings can be legitimate
17                   Extreme weight can be legitimate
18                        High cost can be legitimate
19               High selling price can be legitimate
20  To make cleaned data accessible for analysis a...
21  To ensure consistent results and reproducibili...
Preprocessing log saved successfully!

# Phase 2

# Expand Business Objectives

## Identify Broader Goals Guiding the Project

Increase sales and revenue

Improve customer conversion

Increase customer retention and repeat purchases

Reduce customer churn

Identify and understand high-value customers

Improve customer segmentation and targeting

Understand customer purchasing behaviour

Identify opportunities for personalized marketing

Support data-driven business decision-making

Improve overall customer lifetime value

## Understand Stackholder Needs and Expectations

Management: Needs an overall view of sales, revenue, customer growth, retention, and churn.

Marketing Team: Needs to identify customer segments, conversion opportunities, and customers who need targeted campaigns.

Sales Team: Needs to understand high-value customers, purchasing behaviour, and opportunities to increase sales.

Customer Retention Team: Needs to identify customers at risk of churn and develop retention strategies.

Product Team: Needs to understand product and category performance and customer preferences.

Business Analysts: Need reliable data, meaningful KPIs, statistical evidence, and actionable insights.

Decision Makers: Need clear dashboards, recommendations, limitations, and future opportunities rather than only technical results.

## Define Intended Outcomes from Dataset Analysis

Identify sales and revenue trends.

Understand customer purchasing behaviour.

Identify high-value and low-value customers.

Understand conversion patterns and opportunities.

Measure repeat purchases and customer retention.

Identify customers at risk of churn.

Create meaningful customer segments.

Identify products and categories with strong or weak performance.

Validate important business assumptions using statistical analysis.

Develop actionable business recommendations.

Build Power BI dashboards to support decision-making.

Identify limitations and opportunities for future improvement.

# Generate Business Questions

## Frame Business Questions tied to Objectives

| Business Objective                      | Business Question                                                                                          |
| --------------------------------------- | ---------------------------------------------------------------------------------------------------------- |
| **1. Understand sales performance**     | 1. What are the overall sales, revenue, order volume, and average order value?                             |
|                                         | 2. Which product categories, sub-categories, and products generate the highest revenue?                    |
|                                         | 3. How do sales and revenue vary over time?                                                                |
| **2. Understand customer behavior**     | 4. Who are the highest-value customers based on purchase frequency and spending?                           |
|                                         | 5. How do customer purchasing patterns differ across customer segments?                                    |
|                                         | 6. Which customers are new, repeat, or highly engaged customers?                                           |
| **3. Analyze conversion performance**   | 7. What factors are associated with customers converting from browsing to purchasing?                      |
|                                         | 8. Which traffic sources, devices, or customer segments generate the highest conversion rates?             |
|                                         | 9. Where are the major drop-off points in the customer purchase journey?                                   |
| **4. Measure customer retention**       | 10. What percentage of customers make repeat purchases?                                                    |
|                                         | 11. How does customer retention vary by acquisition source, product category, or customer segment?         |
|                                         | 12. What characteristics distinguish retained customers from one-time customers?                           |
| **5. Identify churn risk**              | 13. Which customers are most likely to become inactive or churn?                                           |
|                                         | 14. What customer behaviors and purchasing patterns are associated with churn?                             |
|                                         | 15. Can customers at high risk of churn be identified early enough for targeted retention campaigns?       |
| **6. Improve profitability**            | 16. Which products and customer segments contribute the most to revenue and profitability?                 |
|                                         | 17. Are there products with high sales but relatively low profit margins?                                  |
|                                         | 18. Which customer segments provide the highest long-term value?                                           |
| **7. Support business decision-making** | 19. Which customer segments should receive targeted marketing or retention strategies?                     |
|                                         | 20. What actionable recommendations can improve sales, conversion, retention, and customer lifetime value? |

## Ensure Questions Are Data-Answerable

| Business Question                                           | Data Required                                                   | Answerable?                                         |
| ----------------------------------------------------------- | --------------------------------------------------------------- | --------------------------------------------------- |
| What are the total sales and revenue?                       | Order, quantity, selling price/revenue                          | ✅ Yes                                               |
| Which products and categories generate the highest revenue? | Product ID, category, selling price, quantity/order data        | ✅ Yes                                               |
| How do sales change over time?                              | Order date, sales/revenue                                       | ✅ Yes                                               |
| Which customers are the highest-value customers?            | Customer ID, order ID, order value                              | ✅ Yes                                               |
| What percentage of customers are repeat customers?          | Customer ID, order ID, order date                               | ✅ Yes                                               |
| Which customer segments generate the most revenue?          | Customer attributes, customer ID, revenue                       | ✅ Yes                                               |
| Which products have the highest profit margins?             | Cost price, selling price, quantity                             | ✅ Yes                                               |
| Which customers are likely to churn?                        | Customer ID, purchase dates, frequency, recency, monetary value | ✅ Yes, if sufficient historical data exists         |
| What factors are associated with customer churn?            | Churn/inactivity indicator + customer behavior variables        | ✅ Yes                                               |
| Which customers should receive retention campaigns?         | Customer behavior + churn-risk/prediction results               | ✅ Yes                                               |
| Which marketing channel has the highest conversion rate?    | Marketing/traffic source + sessions/conversions                 | ⚠️ Only if traffic-source data exists               |
| Where do customers drop off in the purchase journey?        | Session/event/funnel data                                       | ⚠️ Only if journey/event data exists                |
| What is customer satisfaction with the products?            | Ratings, reviews, survey data                                   | ❌ No, if unavailable                                |
| Why do customers leave the company?                         | Churn reason/survey/feedback data                               | ❌ Not directly answerable without churn-reason data |

## Align Questions with Stakeholder Context

The business questions should reflect what different stakeholders need to know to make decisions. For the E-Commerce Customer Analytics project, we can align them as follows:

| Stakeholder                     | Business Need                               | Aligned Business Question                                                                 | Decision Supported                           |
| ------------------------------- | ------------------------------------------- | ----------------------------------------------------------------------------------------- | -------------------------------------------- |
| **Senior Management**           | Understand overall business performance     | What are the key trends in sales, revenue, orders, and customer growth?                   | Business strategy and growth planning        |
| **Sales Team**                  | Improve sales performance                   | Which products, categories, and customer segments generate the highest sales and revenue? | Focus sales efforts on high-performing areas |
| **Marketing Team**              | Improve customer acquisition and conversion | Which customer segments and acquisition channels have the highest conversion rates?       | Optimize marketing campaigns and budgets     |
| **Customer Relationship Team**  | Improve customer retention                  | Which customers are repeat buyers, high-value customers, or becoming inactive?            | Develop targeted retention strategies        |
| **Marketing / CRM Team**        | Reduce customer churn                       | Which customers are at high risk of churn, and what behaviors are associated with churn?  | Launch targeted retention campaigns          |
| **Product / Category Managers** | Improve product performance                 | Which products and categories have high sales, low sales, or low profitability?           | Optimize product assortment and promotions   |
| **Finance Team**                | Improve profitability                       | Which products and customer segments contribute most to revenue and profit?               | Improve pricing and resource allocation      |
| **Data / Analytics Team**       | Support predictive decision-making          | Can customer transaction behavior be used to identify customers likely to churn?          | Build and evaluate a churn prediction model  |

## Convert Business Questions into Structured Hypotheses

The business questions can be converted into testable hypotheses by defining a clear Null Hypothesis (H₀) and Alternative Hypothesis (H₁). This allows the project to validate business assumptions statistically rather than relying only on descriptive analysis.

| Business Question                                                              | Hypothesis                                                          | Null Hypothesis (H₀)                                                                              | Alternative Hypothesis (H₁)                                                                 |
| ------------------------------------------------------------------------------ | ------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------- |
| Which customer segments generate higher revenue?                               | Customer segments differ in spending behavior.                      | There is no significant difference in average spending among customer segments.                   | At least one customer segment has significantly different average spending.                 |
| Does repeat purchasing contribute to higher customer value?                    | Repeat customers generate more revenue than one-time customers.     | There is no significant difference in average revenue between repeat and one-time customers.      | Repeat customers generate significantly higher average revenue.                             |
| Do certain product categories perform better than others?                      | Product categories have different sales performance.                | There is no significant difference in sales/revenue across product categories.                    | At least one category has significantly different sales/revenue.                            |
| Does customer acquisition source affect conversion?                            | Conversion rates vary by acquisition source.                        | Conversion rate is independent of acquisition source.                                             | Conversion rate is significantly associated with acquisition source.                        |
| Does customer engagement influence conversion?                                 | More engaged customers are more likely to convert.                  | Customer engagement has no significant relationship with conversion.                              | Higher customer engagement is significantly associated with higher conversion.              |
| Do customer purchasing patterns differ between retained and churned customers? | Retained and churned customers show different behavioral patterns.  | There is no significant difference in purchasing behavior between retained and churned customers. | Purchasing behavior differs significantly between retained and churned customers.           |
| Can customer behavior predict churn?                                           | Customer behavior can be used to predict churn.                     | Customer behavioral features do not significantly improve churn prediction.                       | Customer behavioral features significantly improve the prediction of churn.                 |
| Do high-value customers have higher purchase frequency?                        | Purchase frequency is associated with customer value.               | There is no significant relationship between purchase frequency and customer value.               | There is a significant positive relationship between purchase frequency and customer value. |
| Does recency influence churn?                                                  | Customers who have not purchased recently are more likely to churn. | Recency has no significant relationship with churn.                                               | Higher recency is significantly associated with increased churn risk.                       |

## Form Assumptions Suitable for Testing

| Business Area           | Testable Assumption                                                                      | Variables Required                                              | Statistical Test |
| ----------------------- | ---------------------------------------------------------------------------------------- | --------------------------------------------------------------- | ---------------- |
| **Customer Value**      | Repeat customers have significantly higher average spending than one-time customers.     | `customer_id`, `order_id`, `customer_type`, `total_spending`    | **T-test**       |
| **Customer Value**      | Frequent customers have significantly higher average spending than infrequent customers. | `customer_id`, `purchase_frequency`, `total_spending`           | **T-test**       |
| **Retention**           | Active and churned customers have significantly different average recency values.        | `customer_id`, `recency`, `churn_status`                        | **T-test**       |
| **Conversion**          | Conversion rates differ significantly between new and returning customers.               | `customer_id`, `customer_type`, `conversion_status`             | **Z-test**       |
| **Conversion**          | Customer conversion is significantly associated with device type.                        | `customer_id/session_id`, `device_type`, `conversion_status`    | **Chi-square**   |
| **Conversion**          | Customer conversion is significantly associated with traffic source.                     | `customer_id/session_id`, `traffic_source`, `conversion_status` | **Chi-square**   |
| **Churn**               | Churn status is significantly associated with customer segment.                          | `customer_id`, `customer_segment`, `churn_status`               | **Chi-square**   |
| **Churn**               | Churn status is significantly associated with purchase-frequency group.                  | `customer_id`, `purchase_frequency_group`, `churn_status`       | **Chi-square**   |
| **Product Performance** | Average selling price differs significantly between two selected product categories.     | `product_id`, `category`, `selling_price`                       | **T-test**       |
| **Sales Performance**   | Average order value differs significantly between two customer groups.                   | `order_id`, `customer_type`, `order_value`                      | **T-test**       |

### Hypotheses

| #      | Hypothesis                                                   | Variables                                    | Test           |
| ------ | ------------------------------------------------------------ | -------------------------------------------- | -------------- |
| **H1** | Repeat customers spend more than one-time customers.         | `customer_type`, `total_spending`            | **T-test**     |
| **H2** | Frequent customers spend more than infrequent customers.     | `purchase_frequency_group`, `total_spending` | **T-test**     |
| **H3** | Active and churned customers have different recency values.  | `churn_status`, `recency`                    | **T-test**     |
| **H4** | Conversion rate differs between new and returning customers. | `customer_type`, `conversion_status`         | **Z-test**     |
| **H5** | Conversion is associated with traffic source.                | `traffic_source`, `conversion_status`        | **Chi-square** |
| **H6** | Churn is associated with customer segment.                   | `customer_segment`, `churn_status`           | **Chi-square** |

## Validate Feasibility Through Initial Checks

Before conducting statistical tests, perform initial checks to confirm that the hypotheses are feasible, data-supported, and suitable for analysis. This prevents testing assumptions that cannot be answered using the available data.

| Initial Check             | What to Verify                                                            | Example for E-Commerce Project                                                  | Feasibility |
| ------------------------- | ------------------------------------------------------------------------- | ------------------------------------------------------------------------------- | ----------- |
| **Data Availability**     | Required variables exist in the datasets.                                 | `customer_type`, `total_spending`, `churn_status`, `recency`, `traffic_source`  | ✅           |
| **Sample Size**           | Each group has enough observations for analysis.                          | Repeat vs. one-time customers should have sufficient records.                   | ✅/⚠️        |
| **Missing Values**        | Important variables do not contain excessive missing values.              | Check missing `total_spending`, `recency`, `conversion_status`.                 | ✅/⚠️        |
| **Data Types**            | Variables have appropriate data types.                                    | Spending should be numeric; churn/conversion should be categorical.             | ✅           |
| **Unique Records**        | Duplicate records do not distort the analysis.                            | Check duplicate `customer_id`, `order_id`, or transaction records.              | ✅           |
| **Group Availability**    | Required comparison groups actually exist.                                | Both repeat and one-time customers must be present.                             | ✅           |
| **Category Availability** | Categories required for Chi-square analysis have sufficient observations. | Multiple traffic sources and conversion outcomes should exist.                  | ✅           |
| **Outliers**              | Extreme values are identified before T-tests.                             | Extremely high customer spending may affect average spending.                   | ⚠️          |
| **Target Variable**       | Outcome variable is clearly defined.                                      | `conversion_status` = Converted/Not Converted; `churn_status` = Churned/Active. | ✅           |
| **Business Relevance**    | The variables and hypothesis relate to a stakeholder decision.            | Identifying churn-related behavior supports retention strategies.               | ✅           |

### Initial Feasibility Checks for the Six Recommended Hypotheses

| Hypothesis                                                          | Required Initial Check                                                                                       |
| ------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------ |
| **H1: Repeat customers spend more than one-time customers.**        | Check `customer_type` and `total_spending`, group sizes, missing values and outliers.                        |
| **H2: Frequent customers spend more than infrequent customers.**    | Check whether purchase-frequency groups can be created and whether both groups have sufficient observations. |
| **H3: Active and churned customers have different recency values.** | Check availability of `recency` and `churn_status`, group sizes and missing values.                          |
| **H4: Conversion differs between new and returning customers.**     | Check `customer_type` and `conversion_status`, and ensure both conversion outcomes exist.                    |
| **H5: Conversion is associated with traffic source.**               | Check `traffic_source` and `conversion_status`, category frequencies and small/empty groups.                 |
| **H6: Churn is associated with customer segment.**                  | Check `customer_segment` and `churn_status`, category frequencies and missing values.                        |

Feasibility Decision

After these checks, classify each hypothesis as:

Feasible – required data is available and sufficiently complete.

Conditionally feasible – data exists but requires cleaning, grouping, or handling of missing/outlier values.

Not feasible – required variables or sufficient observations are unavailable.

This ensures that the project follows a logical process:

Business Question → Assumption → Hypothesis → Initial Data Check → Feasibility → Statistical Test → Business Conclusion.

# Reporting

## Summarize Refined Business Problem Statement

The e-commerce business generates large volumes of customer, order, product, and transaction data but needs to convert this data into actionable insights for better decision-making. The key challenge is to understand sales performance, customer purchasing behavior, conversion, retention, and churn using the available data.

The project will analyze historical customer and transaction data to identify high-value customers, purchasing patterns, product and category performance, conversion behavior, and factors associated with customer retention and churn. Statistical techniques such as Z-tests, T-tests, and Chi-square tests will be used to validate selected business assumptions and determine whether observed patterns are statistically significant.

The analysis will provide stakeholders with evidence-based insights to help improve sales, increase customer conversion, strengthen retention strategies, identify potential churn risks, and support more effective business decisions.

Refined Problem Statement:

How can e-commerce customer, order, product, and transaction data be analyzed and statistically validated to identify factors influencing sales, customer value, conversion, retention, and churn, and translate these findings into actionable business strategies?

## Document Null and Alternate hypotheses clearly

# Null and Alternative Hypotheses

The hypotheses are formulated from the refined business questions and are designed to be tested using the statistical methods covered in the project: **T-test, Z-test, and Chi-square test**.

| Hypothesis                             | Null Hypothesis (H₀)                                                                                  | Alternative Hypothesis (H₁)                                                                  | Test       |
| -------------------------------------- | ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- | ---------- |
| **H1 – Customer Value**                | There is **no significant difference** in average spending between repeat and one-time customers.     | Repeat customers have **significantly higher average spending** than one-time customers.     | T-test     |
| **H2 – Purchase Frequency**            | There is **no significant difference** in average spending between frequent and infrequent customers. | Frequent customers have **significantly higher average spending** than infrequent customers. | T-test     |
| **H3 – Retention and Recency**         | There is **no significant difference** in average recency between active and churned customers.       | Active and churned customers have a **significantly different average recency**.             | T-test     |
| **H4 – Customer Type and Conversion**  | There is **no significant difference** in conversion rates between new and returning customers.       | Conversion rates are **significantly different** between new and returning customers.        | Z-test     |
| **H5 – Traffic Source and Conversion** | Customer conversion is **independent of traffic source**.                                             | Customer conversion is **significantly associated with traffic source**.                     | Chi-square |
| **H6 – Customer Segment and Churn**    | Customer churn is **independent of customer segment**.                                                | Customer churn is **significantly associated with customer segment**.                        | Chi-square |

## Decision Rule

All hypotheses will be evaluated at a **5% significance level (α = 0.05)**.

* **If p-value < 0.05:** Reject H₀ and support H₁.
* **If p-value ≥ 0.05:** Fail to reject H₀.

The final conclusion should be based on the statistical test results and should be translated into a **business interpretation**, rather than reporting only whether the hypothesis was accepted or rejected.

### Example

**Business Question:** Do repeat customers spend more than one-time customers?

* **H₀:** There is no significant difference in average spending between repeat and one-time customers.
* **H₁:** Repeat customers have significantly higher average spending than one-time customers.
* **Test:** Independent two-sample T-test
* **Significance Level:** α = 0.05
* **Decision:** Compare the calculated p-value with 0.05.
* **Business Interpretation:** Determine whether repeat customers should be prioritized through customer retention and loyalty strategies.

## Expected Direction and Tail Type

For each hypothesis, document whether the expected relationship is directional or non-directional, and select the appropriate tail of the statistical test.

| Hypothesis                             | Expected Direction                                               | Tail Type                           | Reason                                                                                                                                                  |
| -------------------------------------- | ---------------------------------------------------------------- | ----------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **H1 – Repeat Customers & Spending**   | Repeat customers **spend more** than one-time customers.         | **One-tailed (right-tailed)**       | The assumption predicts a specific direction: higher spending.                                                                                          |
| **H2 – Purchase Frequency & Spending** | Frequent customers **spend more** than infrequent customers.     | **One-tailed (right-tailed)**       | The assumption predicts higher spending for frequent customers.                                                                                         |
| **H3 – Retention & Recency**           | Active and churned customers have **different** recency values.  | **Two-tailed**                      | No specific direction is assumed; only that the averages differ.                                                                                        |
| **H4 – Customer Type & Conversion**    | New and returning customers have **different** conversion rates. | **Two-tailed**                      | The hypothesis does not specify which group has the higher conversion rate.                                                                             |
| **H5 – Traffic Source & Conversion**   | Conversion is **associated with** traffic source.                | **Chi-square test of independence** | Chi-square tests whether the categorical variables are associated; it does not use one-/two-tailed direction in the same way as a mean/proportion test. |
| **H6 – Customer Segment & Churn**      | Churn is **associated with** customer segment.                   | **Chi-square test of independence** | The hypothesis tests whether the two categorical variables are related.                                                                                 |